Make pyproj optional
Because I'm trying to create a single file executable with
PyInstaller and it doesn't include the pyproj.datadir
with the package.

  File "site-packages/pyproj/__init__.py", line 70, in <module>
  File "pyproj/_datadir.pyx", line 6, in init pyproj._datadir
ModuleNotFoundError: No module named 'pyproj.datadir'